/* Automatically generated by wasm2c */
#ifndef ZIG_JSON_H_GENERATED_
#define ZIG_JSON_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct Z_wasi_snapshot_preview1_instance_t;

typedef struct Z_zigZ2Djson_instance_t {
  struct Z_wasi_snapshot_preview1_instance_t* Z_wasi_snapshot_preview1_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} Z_zigZ2Djson_instance_t;

void Z_zigZ2Djson_init_module(void);
void Z_zigZ2Djson_instantiate(Z_zigZ2Djson_instance_t*, struct Z_wasi_snapshot_preview1_instance_t*);
void Z_zigZ2Djson_free(Z_zigZ2Djson_instance_t*);

/* import: 'wasi_snapshot_preview1' 'args_get' */
u32 Z_wasi_snapshot_preview1Z_args_get(struct Z_wasi_snapshot_preview1_instance_t*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
u32 Z_wasi_snapshot_preview1Z_args_sizes_get(struct Z_wasi_snapshot_preview1_instance_t*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
u32 Z_wasi_snapshot_preview1Z_fd_read(struct Z_wasi_snapshot_preview1_instance_t*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 Z_wasi_snapshot_preview1Z_fd_write(struct Z_wasi_snapshot_preview1_instance_t*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void Z_wasi_snapshot_preview1Z_proc_exit(struct Z_wasi_snapshot_preview1_instance_t*, u32);

/* export: 'memory' */
wasm_rt_memory_t* Z_zigZ2DjsonZ_memory(Z_zigZ2Djson_instance_t* instance);

/* export: '_start' */
void Z_zigZ2DjsonZ__start(Z_zigZ2Djson_instance_t*);

#ifdef __cplusplus
}
#endif

#endif  /* ZIG_JSON_H_GENERATED_ */
